// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARfG6HvCMYly3EUOkgsbPA_j6QN9dQuRQ',
    appId: '1:329404137758:web:54ed1dbd3b45360858c90f',
    messagingSenderId: '329404137758',
    projectId: 'opentrail-app',
    authDomain: 'opentrail-app.firebaseapp.com',
    databaseURL: 'https://opentrail-app-default-rtdb.firebaseio.com',
    storageBucket: 'opentrail-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEglAwK4ik8UiJ6jV-r5aA_N_qFL9aL4Y',
    appId: '1:329404137758:android:202cc00a76b35a9a58c90f',
    messagingSenderId: '329404137758',
    projectId: 'opentrail-app',
    databaseURL: 'https://opentrail-app-default-rtdb.firebaseio.com',
    storageBucket: 'opentrail-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0EZ9xVpODWoj9sgB17KmrR1LdFkHT7r4',
    appId: '1:329404137758:ios:bdc7f5bbf53f6ed658c90f',
    messagingSenderId: '329404137758',
    projectId: 'opentrail-app',
    databaseURL: 'https://opentrail-app-default-rtdb.firebaseio.com',
    storageBucket: 'opentrail-app.firebasestorage.app',
    iosBundleId: 'com.example.openTrail',
  );
}
